apiVersion: v2
name: appsphere
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
appVersion: "1.16.0"

annotations:
  artifacthub.io/oci: "true"
  artifacthub.io/ociRegistry: ghcr.io
  artifacthub.io/ociRepository: rohit27305/helm-charts
  artifacthub.io/maintainers: |
    - name: Rohit
      email: rohitverma27305@gmail.com
  artifacthub.io/license: Apache-2.0
  artifacthub.io/category: networking