{{- if and .Values.rbac .Values.rbac.enabled .Values.rbac.cluster.enabled }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Values.rbac.cluster.roleName }}
  labels:
    {{- include "appshpere.labels" . | nindent 4 }}
rules:
  {{- toYaml .Values.rbac.cluster.rules | nindent 2 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Values.rbac.cluster.roleBindingName }}
  labels:
    {{- include "appshpere.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ .Values.rbac.cluster.serviceAccountName }}
    namespace: {{ .Values.global.namespace }}
roleRef:
  kind: ClusterRole
  name: {{ .Values.rbac.cluster.roleName }}
  apiGroup: rbac.authorization.k8s.io
{{- end }}
