{{- if and .Values.rbac .Values.rbac.enabled .Values.rbac.namespace.enabled }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .Values.rbac.namespace.roleName }}
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "appshpere.labels" . | nindent 4 }}
rules:
  {{- toYaml .Values.rbac.namespace.rules | nindent 2 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Values.rbac.namespace.roleBindingName }}
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "appshpere.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ .Values.rbac.namespace.serviceAccountName }}
    namespace: {{ .Values.global.namespace }}
roleRef:
  kind: Role
  name: {{ .Values.rbac.namespace.roleName }}
  apiGroup: rbac.authorization.k8s.io
{{- end }}
